# tmp to make dumpVTK utility


dumpVTK: dumpVTK.cpp bubbles/Mesh.hpp bubbles/FileInput.hpp
	g++ -g -O3 -I/usr/include/eigen3 dumpVTK.cpp -o dumpVTK -lboost_regex -lboost_filesystem -lboost_system -lvtkIOXML -lvtkCommonDataModel -lvtkCommonCore
